version: '3.3'

services:
  mock-api:
    build: .
    ports:
      - "8989:8989"
    volumes:
      - .:/app
      - ./../../../static:/app/static
    env_file:
        - ./../../../.env
    command: nodemon --watch . index.php
