version: '3.3'

services:
  mock-api:
    build: .
    ports:
      - "${PORT}:${PORT}"
    networks:
      - "${NETWORK}"
    volumes:
      - .:/app
      - ./../../../static:/app/static
    env_file:
        - ./../../../.mock-api-env
    command: nodemon --watch . index.php
