version: '3.3'

services:
  mock-api:
    build: .
    ports:
      - "${PORT}:${PORT}"
    networks:
      - "${NETWORK}"
    env_file:
      - .env.external
    volumes:
      - .:/app
      - ./../../../static:/app/static
    command: nodemon --watch . index.php
